name: Install Windows SDK
description: Installs the required Windows SDKs to target release 1803

runs:
  using: composite

  steps:
    - id: install-sdk-windows
      if: runner.os == 'Windows'
      run: ${{ github.workspace }}\dependencies\windows10-sdk-1803\install.ps1
      shell: pwsh
