name: Sign Windows Binaries
description: Sign the Windows Binaries using an x.509 certificate

inputs:
  bin-folder:
    description: 'The folder holding the binaries to sign'
    required: true
  production:
    description: 'Flag whether sign in production mode (true = production, false = development)'
    required: true
  azure-keyvault-uri:
    description: 'The Azure KeyVault URI holding the certificate'
    required: true
  timestamp-uri:
    description: 'The Timestamp service URI, required of production=true'
    required: false
    default: ''
  certificate-name:
    description: 'The Azure KeyVault Certificate Name'
    required: true
  tenant-id:
    description: 'The Tenant ID of the Entra ID Application accessing KeyVault'
    required: true
  client-id:
    description: 'The Client ID of the Entra ID Application accessing KeyVault'
    required: true
  client-secret:
    description: 'The Client Secret of the Entra ID Application accessing KeyVault'
    required: true
  
runs:
  using: composite

  steps:
    # Install AzureSignTool and ignore any the exit code as the tool might be already installed
    - id: install-azuresigntool
      name: 'Sign: install AzureSignTool'
      if: runner.os == 'Windows'
      run: | 
        dotnet tool install --global AzureSignTool
        return
      shell: pwsh

    - id: collect-binaries
      name: 'Sign: collect binaries to sign'
      run: |
        $file = New-TemporaryFile
        Get-ChildItem -Path "${{ inputs.bin-folder }}\*" -Include *.dll, *.exe | ForEach-Object { Add-Content -Path $file $_.FullName } 
        Write-Output "files=$file" >> "$env:GITHUB_OUTPUT"
      shell: pwsh

    # Sign the binaries in production mode (aka timestamp)
    - name: 'Sign: Production signing binaries'
      if: inputs.production == 'true'
      run: > 
        azuresigntool sign --file-digest sha256
        --azure-key-vault-url ${{ inputs.azure-keyvault-uri }}
        --azure-key-vault-certificate ${{ inputs.certificate-name }}
        --azure-key-vault-tenant-id ${{ inputs.tenant-id }} 
        --azure-key-vault-client-id ${{ inputs.client-id }} 
        --azure-key-vault-client-secret ${{ inputs.client-secret }}
        --timestamp-rfc3161 ${{ inputs.timestamp-uri }} --timestamp-digest sha256
        --input-file-list ${{ steps.collect-binaries.outputs.files }}
      shell: pwsh

    # Sign the binaries in development mode - signature is expected to expire
    - name: 'Sign: DEV signing binaries'
      if: inputs.production == 'false'
      run: > 
        azuresigntool sign --file-digest sha256
        --azure-key-vault-url ${{ inputs.azure-keyvault-uri }}
        --azure-key-vault-certificate ${{ inputs.certificate-name }}
        --azure-key-vault-tenant-id ${{ inputs.tenant-id }} 
        --azure-key-vault-client-id ${{ inputs.client-id }} 
        --azure-key-vault-client-secret ${{ inputs.client-secret }}
        --input-file-list ${{ steps.collect-binaries.outputs.files }}
      shell: pwsh

