name: Build and Test Flutter App
description: Builds a flutter app and runs unit tests
inputs:
  project-folder:
    description: 'The folder where the app to build is located'
    required: true

  project-prefix:
    description: 'The folder prefix for artifacts'
    required: true

runs:
  using: composite

  steps:
    - name: "${{project-prefix}}: Fetch Flutter dependencies"
      working-directory: ${{ inputs.project-folder }}
      run: flutter pub get
      shell: pwsh

    - name: "${{project-prefix}}: Build runner"
      working-directory: ${{ inputs.project-folder }}
      run: dart run build_runner build --delete-conflicting-outputs
      shell: pwsh

    - name: "${{project-prefix}}: Run Dart license checker"
      run: |
        dart pub global activate license_checker_for_github_action
        dart_license_checker --show-transitive-dependencies --fail-on-copyleft
      shell: pwsh
