name: Create Windows Debug Symbols Bundle
description: Create a folder holding App and Background Agent symbols
inputs:
  build-dir:
    description: "Directory where the action should build the bundle"
    required: true
  app-release-symbols-dir:
    description: "app symbols directory"
    required: false
    default: belimo_assistant\debug_symbols
  agent-release-symbol-dir:
    description: "background agent symbols directory"
    required: false
    default: background_agent\debug_symbols
outputs:
  path:
    description: "The path to the symbols"
    value: ${{ steps.bundle.outputs.path }}

runs:
  using: composite

  steps:
    - name: Bundle symbols into folder
      id: bundle
      run: |
        New-Item -ItemType "directory" -Path ${{ inputs.build-dir }}
        Copy-Item -Path "${{ inputs.app-release-symbols-dir }}" -Destination "${{ inputs.build-dir }}\belimo_assistant" -Recurse
        Copy-Item -Path "${{ inputs.app-release-symbols-dir }}" -Destination "${{ inputs.build-dir }}\background_agent" -Recurse
        Write-Output "path=${{ inputs.build-dir }}" >> "$env:GITHUB_OUTPUT"
      shell: pwsh
