name: Create Changelog
description: Writes the commit messages to a markdown file and formats them in an appropriate manner.
inputs:
  diff-from:
    description: 'The git ref to start changelog from. The commit message of this ref will not be included in the changelog. diff-from must be an ancestor of diff-to.'
    required: true
  diff-to:
    description: 'The git ref to start changelog from. The commit message of this ref will not be included in the changelog. diff-to must be a descendant of diff-from.'
    required: true
  changelog-filepath:
    description: 'The file path to save the license report to. Expects a .md file extension. In case of a relative path, it will be relative to the repo root.'
    required: true
  upload-artifact:
    description: 'Boolean whether to upload as GitHub Actions artifact.'
    required: false
    default: 'false'
runs:
  using: composite
  steps:
    - name: Create Changelog
      shell: bash
      run: |
        # Captures Jira ticket and PR identifiers using extended regular expressions (-r) and replaces them with a link to the respective page. The captured identifiers is referenced using \1.
        git log --format="%s" ${{ inputs.diff-from }}..${{ inputs.diff-to }} `# Lists the commit messages (%s) of all commits between diff-from (excluded) and diff-to (included)` \
            | sed 's/^/- /' `# Create an unordered markdown list by prepending each line with '- '` \
            | sed -r 's/(IOTECO-[0-9]+)/[\1](https:\/\/jira.belimo\.ch\/browse\/\1)/g' `# Replace any Jira ticket number ('IOTECO-xxx') with the respective link` \
            | sed -r 's/ \(#([0-9]+)\)/ ([#\1](https:\/\/github.com\/BelimoAutomationAG\/belimo_assistant\/pull\/\1))/g' `# Replace any PR number (' (#xxx)' at the end of line) with the respective link` \
            > ${{ inputs.changelog-filepath }}
    - name: Upload Changelog
      if: ${{ inputs.upload-artifact == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: changelog
        path: ./${{ inputs.changelog-filepath }}
