name: Create Build Number
description: Retrieves a build number stored as GitHub Variable, increments it, and returns the incremented build number. Can be used for different kinds of builds by separating the build numbers with different variable names. The scope of the build number is bound to the scope of the provided GitHub Variable.
inputs:
  token:
    description: GitHub Token to read and update GitHub Variable (GITHUB_TOKEN), requires repo scope
    required: true
  build-number-var-name:
    description: Name of the GitHub Variable to store the build number in
    required: true
outputs:
  build-number:
    description: Build number
    value: ${{ steps.build-number.outputs.build-number }}
runs:
  using: composite

  steps:
    - name: Increment and output build number
      id: build-number
      uses: actions/github-script@v7
      with:
        result-encoding: string
        github-token: ${{ inputs.token }}
        script: |
          // Get the current build number from GitHub Vars
          let buildNumberResponse = await github.rest.actions.getRepoVariable({
            name: "${{ inputs.build-number-var-name }}",
            owner: context.repo.owner,
            repo: context.repo.repo,
          })
          let buildNumber = buildNumberResponse.data.value;
          if (!Number.isInteger(parseInt(buildNumber))) {
            core.setFailed(`${{ inputs.build-number-var-name }} with value '${buildNumber}' is not a valid build number.`);
          }

          // Increment the build number var. Reasoning to increment before setting the output: If the vars.BUILD_NUMBER is accessed in the same workflow, it's consistent with the output.
          const incrementedBuildNumber = (++buildNumber).toString();
          await github.rest.actions.updateRepoVariable({
            name: "${{ inputs.build-number-var-name }}",
            value: incrementedBuildNumber,
            owner: context.repo.owner,
            repo: context.repo.repo,
          });

          // Set the build number as output
          core.setOutput("build-number", incrementedBuildNumber)
