# Tool: https://docs.github.com/en/code-security/dependabot
# Checks for vulnerabilities in the Pub package manager
version: 2
updates:
  - package-ecosystem: "pub" # See documentation for possible values
    directory: "/belimo_assistant/" # Location of package manifests
    schedule:
      interval: "daily"
    target-branch: "main"
    open-pull-requests-limit: 0
