name: Sign Windows Installer
description: Sign the Windows Installer using an x.509 certificate

inputs:
  file-to-sign:
    description: "The file to sign"
    required: true
  sign-tool:
    description: "Path to the signtool"
    required: true
  certificate:
    description: "Path to the signing certificate"
    required: true
  password:
    description: "Password for the signing certificate"
    required: true

runs:
  using: composite

  steps:
    - name: "Signing installer"
      run: ${{ github.action_path }}\sign.ps1 -File "${{ inputs.file-to-sign }}" -Cert ${{ inputs.certificate }} -Password ${{ inputs.password }} -SignTool ${{ inputs.sign-tool }}
      shell: pwsh
