name: Sign Windows Binaries
description: Sign the Windows Binaries using an x.509 certificate

inputs:
  bin-folder:
    description: 'The folder holding the binaries to sign'
    required: true
  sign-tool:
    description: 'Path to the signtool'
    required: true
  certificate:
    description: 'Path to the signing certificate'
    required: true
  password:
    description: 'Password for the signing certificate'
    required: true

runs:
  using: composite

  steps:
    - name: 'Signing binaries'
      run: ${{ github.action_path }}\sign.ps1 -Path ${{ inputs.bin-folder }} -Cert ${{ inputs.certificate }} -Password ${{ inputs.password }} -SignTool ${{ inputs.sign-tool }}
      shell: pwsh

