name: "Git: config credential cache"
description: Configures the Git Credential Cache/Manager

inputs:
  private-repos-user-pat:
    description: 'A Github PAT'
    required: true

runs:
  using: composite

  steps:
  - id: windows-git-config-longpath
    if: runner.os == 'Windows'
    shell: pwsh
    run: git config --global core.longpaths true

  - id: windows-git-configure-cache
    name: "Windows: config credential cache"
    if: runner.os == 'Windows'
    shell: pwsh
    run: Write-Output "protocol=https`r`nhost=github.com`r`nusername=nonce`r`npassword=${{ inputs.private-repos-user-pat }}`r`n`r`n" | git credential-manager store

  - id: unix-git-configure-cache
    if: runner.os != 'Windows'
    shell: bash
    run: |
        git config --global credential.helper 'cache --timeout 1800'
        echo -e "protocol=https\nhost=github.com\nusername=nonce\npassword=${{ inputs.private-repos-user-pat }}\n\n" | git credential-cache store
