name: Create Translation Report
description: |
  Creates a report of untranslated texts from the Flutter project and the UI Profiles.
inputs:
  project-directory:
    description: The flutter project directory
    required: true
  arb-export-filepath:
    description: Filepath to the export file containing the untranslated .arb labels
    required: true
  ui-profile-export-filepath:
    description: Filepath to the export file containing the untranslated UI Profile labels
    required: true
  upload-artifacts:
    description: Boolean whether to upload as GitHub Actions artifact
    required: false
    default: 'false'
runs:
  using: composite
  steps:
    - shell: bash
      working-directory: ${{ inputs.project-directory }}
      run: dart pub get
    - name: Export untranslated ARB labels
      shell: bash
      working-directory: ${{ inputs.project-directory }}
      run: dart run ./scripts/translation_export/export_untranslated_arb_labels.dart -a ./lib/ui/l10n -o ${{ inputs.arb-export-filepath }}
    - name: Export untranslated UI Profile labels
      shell: bash
      working-directory: ${{ inputs.project-directory }}
      run: dart run ./scripts/translation_export/export_untranslated_ui_profile_labels.dart -p ./assets/profiles/ui_profiles -o ${{ inputs.ui-profile-export-filepath }}
    - name: Upload translation report
      if: ${{ inputs.upload-artifacts == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: translation-report
        path: |
          ${{ inputs.project-directory}}/${{ inputs.arb-export-filepath }}
          ${{ inputs.project-directory}}/${{ inputs.ui-profile-export-filepath }}
