name: Create Windows App Bundle
description: Create a folder holding App and BackgroundAgent binaries
inputs:
  build-dir:
    description: "Directory where the action should build the bundle"
    required: true
  app-release-bin-dir:
    description: "app bin directory"
    required: false
    default: belimo_assistant\build\windows\x64\runner\Release
  agent-release-bin-dir:
    description: "background agent bin directory"
    required: false
    default: background_agent\build\windows\x64\runner\Release
outputs:
  path:
    description: "The path to the app bundle"
    value: ${{ steps.bundle.outputs.path }}

runs:
  using: composite

  steps:
    - name: Bundle files into folder
      id: bundle
      run: |
        New-Item -ItemType "directory" -Path ${{ inputs.build-dir }}
        Copy-Item -Path "${{ inputs.app-release-bin-dir }}" -Destination "${{ inputs.build-dir }}\belimo_assistant" -Recurse
        Copy-Item -Path "${{ inputs.agent-release-bin-dir }}" -Destination "${{ inputs.build-dir }}\background_agent" -Recurse
        Write-Output "path=${{ inputs.build-dir }}" >> "$env:GITHUB_OUTPUT"
      shell: pwsh
